version: "3"
services:
  app:
    build: .
#    image: php:7.4.1-apache
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=docker_test
